{% set name = "pari_jupyter" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 7cd9291d05b92b8303c6ae8cf25622e5ecbab1ac2bcf13911f900ea987471b9d

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  skip: true  # [py>312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython <3
    - pip
    - setuptools
    - pari
    - readline
  run:
    - python
    - pari
    - readline

test:
  imports:
    - PARIKernel

about:
  home: https://github.com/sagemath/pari_jupyter
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Jupyter kernel for PARI/GP
  dev_url: https://github.com/sagemath/pari_jupyter

extra:
  recipe-maintainers:
    - conda-forge/pari
